/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as CockpitRouteImport } from './routes/cockpit'
import { Route as CompanyBrainRouteImport } from './routes/company-brain'
import { Route as CopilotsRouteImport } from './routes/copilots'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as WorkflowStudioRouteImport } from './routes/workflow-studio'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as DepartmentsDeptIdRouteImport } from './routes/departments.$deptId'
import { Route as MSlugRouteImport } from './routes/m.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitRoute = CockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyBrainRoute = CompanyBrainRouteImport.update({
  id: '/company-brain',
  path: '/company-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotsRoute = CopilotsRouteImport.update({
  id: '/copilots',
  path: '/copilots',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowStudioRoute = WorkflowStudioRouteImport.update({
  id: '/workflow-studio',
  path: '/workflow-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDeptIdRoute = DepartmentsDeptIdRouteImport.update({
  id: '/departments/$deptId',
  path: '/departments/$deptId',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/cockpit': typeof CockpitRoute
  '/company-brain': typeof CompanyBrainRoute
  '/copilots': typeof CopilotsRoute
  '/documents': typeof DocumentsRoute
  '/workflow-studio': typeof WorkflowStudioRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/m/$slug': typeof MSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/cockpit': typeof CockpitRoute
  '/company-brain': typeof CompanyBrainRoute
  '/copilots': typeof CopilotsRoute
  '/documents': typeof DocumentsRoute
  '/workflow-studio': typeof WorkflowStudioRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/m/$slug': typeof MSlugRoute
  '/agents': typeof AgentsIndexRoute
  '/departments': typeof DepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/cockpit': typeof CockpitRoute
  '/company-brain': typeof CompanyBrainRoute
  '/copilots': typeof CopilotsRoute
  '/documents': typeof DocumentsRoute
  '/workflow-studio': typeof WorkflowStudioRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/m/$slug': typeof MSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/cockpit'
    | '/company-brain'
    | '/copilots'
    | '/documents'
    | '/workflow-studio'
    | '/agents/$agentId'
    | '/departments/$deptId'
    | '/m/$slug'
    | '/agents/'
    | '/departments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/cockpit'
    | '/company-brain'
    | '/copilots'
    | '/documents'
    | '/workflow-studio'
    | '/agents/$agentId'
    | '/departments/$deptId'
    | '/m/$slug'
    | '/agents'
    | '/departments'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/cockpit'
    | '/company-brain'
    | '/copilots'
    | '/documents'
    | '/workflow-studio'
    | '/agents/$agentId'
    | '/departments/$deptId'
    | '/m/$slug'
    | '/agents/'
    | '/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutomationRoute: typeof AutomationRoute
  CockpitRoute: typeof CockpitRoute
  CompanyBrainRoute: typeof CompanyBrainRoute
  CopilotsRoute: typeof CopilotsRoute
  DocumentsRoute: typeof DocumentsRoute
  WorkflowStudioRoute: typeof WorkflowStudioRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  DepartmentsDeptIdRoute: typeof DepartmentsDeptIdRoute
  MSlugRoute: typeof MSlugRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit': {
      id: '/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof CockpitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-brain': {
      id: '/company-brain'
      path: '/company-brain'
      fullPath: '/company-brain'
      preLoaderRoute: typeof CompanyBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilots': {
      id: '/copilots'
      path: '/copilots'
      fullPath: '/copilots'
      preLoaderRoute: typeof CopilotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-studio': {
      id: '/workflow-studio'
      path: '/workflow-studio'
      fullPath: '/workflow-studio'
      preLoaderRoute: typeof WorkflowStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$deptId': {
      id: '/departments/$deptId'
      path: '/departments/$deptId'
      fullPath: '/departments/$deptId'
      preLoaderRoute: typeof DepartmentsDeptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutomationRoute: AutomationRoute,
  CockpitRoute: CockpitRoute,
  CompanyBrainRoute: CompanyBrainRoute,
  CopilotsRoute: CopilotsRoute,
  DocumentsRoute: DocumentsRoute,
  WorkflowStudioRoute: WorkflowStudioRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  DepartmentsDeptIdRoute: DepartmentsDeptIdRoute,
  MSlugRoute: MSlugRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
